concurrent = 3
check_interval = 10
log_level = "debug"

[[runners]]
  name = "$NAME"
  url = "$URL"
  token = "$RUNNER_TOKEN"
  executor = "custom"
  builds_dir = "/opt/gitlab-runner/builds"
  cache_dir = "/opt/gitlab-runner/cache"
  [runners.custom]
    config_exec = "/opt/gitlab-runner/fargate/fargate"
    config_args = ["--config", "/opt/gitlab-runner/fargate/config.toml", "custom", "config"]
    prepare_exec = "/opt/gitlab-runner/fargate/fargate"
    prepare_args = ["--config", "/opt/gitlab-runner/fargate/config.toml", "custom", "prepare"]
    run_exec = "/opt/gitlab-runner/fargate/fargate"
    run_args = ["--config", "/opt/gitlab-runner/fargate/config.toml", "custom", "run"]
    cleanup_exec = "/opt/gitlab-runner/fargate/fargate"
    cleanup_args = ["--config", "/opt/gitlab-runner/fargate/config.toml", "custom", "cleanup"]
